### ISSUE TITLE
Jira Integration: Tasks to be fetched from Jira board

### ISSUE THREAD

**Issue by attriaayush** [TresAmigosLtd/pair_dance#41]
It would be nice to automatically sync the task lifecycle to the tasks on your team's working board. The idea would be to use team's working Jira board for instance to automatically stay in sync with the task creation/deletion as things move from `in_progress` to `done` instead of maintaining the tasks on two different platforms. 

Is that something we would like to tackle soon? 😄 

I will be more than happy to contribute if there is an appetite for that.

**Comment by bengro** [comment]
There is a huge appetite for that! 

The Jira integration (alongside Google Calendar to indicate pairing availability) are top of the list. Contributions will be rewarded!
